cfg = {
    "features": [
        "ANOM_autocorr",
        "ANOM_roll_max5",
        "ANOM_roll_mean5",
        "ANOM_roll_min5",
        "INDEX_1",
        "INDEX_10",
        "INDEX_3",
        "INDEX_4",
        "INDEX_5",
        "INDEX_6",
        "INDEX_7",
        "INDEX_8",
        "INDEX_9",
        "NINO1+2",
        "NINO3",
        "NINO3 ANOM",
        "NINO3.4",
        "NINO3.4 ANOM",
        "NINO4",
        "NINO4 ANOM",
        "PREC_DAILY",
        "WTEQ_DAILY",
        "basins_area",
        "cos_yr2_1",
        "cos_yr3_1",
        "distance_station",
        "distance_station_RAIN",
        "distance_station_SNOW WC",
        "elevation",
        "elevation_station",
        "latitude",
        "latitude_station",
        "latitude_station_RAIN",
        "latitude_station_SNOW WC",
        "longitude",
        "longitude_station",
        "longitude_station_RAIN",
        "longitude_station_SNOW WC",
        "issue_month",
        "pdo_index",
        "pdo_index_roll_mean5",
        "pdo_index_roll_std7",
        "pdsi_1",
        "pdsi_2",
        "pna_index",
        "pna_index_autocorr",
        "sin_yr2_1",
        "sin_yr3_1",
        "site_id",
        "soi_roll_mean5",
        "stations_count",
        "value_RAIN",
        "value_SNOW WC",
        "volume_ewm_mean7",
        "volume_roll_max5",
        "volume_roll_mean5",
        "volume_roll_min5",
        "volume_roll_std7",
    ],
    "year_weights": {"start_year": 2000, "scale": 1},
    "volume_weights": {"baseline": 1, "scale": 4},
    "forecast_year_cutoff": 1951,
    "cv_splits": 5,
}
